---
- hosts: localhost

  roles:
      - role: packages
        become: yes
        become_user: root
      - role: configs
      - role: npm
        become: yes
        become_user: root
      # - role: intel_driver
      - role: ctags-build
      - role: radare2
