---
- hosts: localhost
  # environment:
  #     http_proxy: <proxy>
  #     https_proxy: <proxy>
  become_user: ichuraev

  roles:
      - role: packages
      - role: configs
      - role: ranger
      - role: radare2
