---
- stat: path=~/projects/dotfiles
  register: dot_dir

- name: Download dotfiles
  git:
      repo: 'https://github.com/ilyachur/dotfiles'
      dest: ~/projects/dotfiles
  when: dot_dir.stat.exists == False

- name: Install dotfiles
  shell: ~/projects/dotfiles/install.sh
  when: dot_dir.stat.exists == False

- stat: path="/usr/share/fonts/Literation Mono Nerd Font Complete Mono.ttf"
  when: ansible_distribution != 'MacOSX'
  register: lin_font_installed

- stat: path="~/Library/Fonts/Literation Mono Nerd Font Complete Mono.ttf"
  when: ansible_distribution == 'MacOSX'
  register: mac_font_installed

- name: Install font
  get_url: dest="/usr/share/fonts/Literation Mono Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
  when: ansible_distribution != 'MacOSX' and lin_font_installed.stat.exists == False
  become: yes
  become_user: root
- name: Install font
  get_url: dest="~/Library/Fonts/Literation Mono Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
  when: ansible_distribution == 'MacOSX' and mac_font_installed.stat.exists == False

- name: Install italic font
  get_url: dest="/usr/share/fonts/Literation Mono Italic Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Italic%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
  when: ansible_distribution != 'MacOSX' and lin_font_installed.stat.exists == False
  become: yes
  become_user: root
- name: Install italic font
  get_url: dest="~/Library/Fonts/Literation Mono Italic Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Italic%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
  when: ansible_distribution == 'MacOSX' and mac_font_installed.stat.exists == False

- name: Install bold font
  get_url: dest="/usr/share/fonts/Literation Mono Bold Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Bold%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
  when: ansible_distribution != 'MacOSX' and lin_font_installed.stat.exists == False
  become: yes
  become_user: root
- name: Install bold font
  get_url: dest="~/Library/Fonts/Literation Mono Bold Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Bold%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
  when: ansible_distribution == 'MacOSX' and mac_font_installed.stat.exists == False

- stat: path=/usr/local/bin/vim
  when: ansible_distribution == 'MacOSX' 
  register: local_vim

- name: Set vim as an editor for git
  shell: git config --global core.editor vim

- name: Link MacVim to local bin
  shell: ln -s /Applications/MacVim.app/Contents/bin/vim /usr/local/bin/vim
  when: ansible_distribution == 'MacOSX' and local_vim.stat.exists == False

- name: Check status of hidden files
  command: defaults read com.apple.Finder AppleShowAllFiles
  when: ansible_distribution == 'MacOSX' 
  register: mac_hidden_check

- name: Show hidden files in Mac Finder
  shell: defaults write com.apple.Finder AppleShowAllFiles true && killall Finder
  when: ansible_distribution == 'MacOSX' and "false" in mac_hidden_check.stdout

- name: Init vim packages
  shell: yes "" | vim +PlugInstall +qall
  when: dot_dir.stat.exists == False
