---
- stat: path=~/projects/dotfiles
  register: dot_dir

- name: Download dotfiles
  git:
      repo: 'https://github.com/ilyachur/dotfiles'
      dest: ~/projects/dotfiles
  when: dot_dir.stat.exists == False

- name: Install dotfiles
  shell: ~/projects/dotfiles/install.sh
  when: dot_dir.stat.exists == False

- stat: path="/usr/share/fonts/Literation Mono Powerline Nerd Font Complete Mono.ttf"
  when: ansible_distribution == 'MacOSX' or ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  register: font_installed

- name: Install font
  get_url: dest="~/Library/Fonts/Literation Mono Powerline Nerd Font Complete Mono.ttf" url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/LiberationMono/complete/Literation%20Mono%20Nerd%20Font%20Complete%20Mono.ttf
  when: ansible_distribution == 'MacOSX' and font_installed.stat.exists == False

- stat: path=/usr/local/bin/vim
  when: ansible_distribution == 'MacOSX' 
  register: local_vim

- name: Link MacVim to local bin
  shell: ln -s /Applications/MacVim.app/Contents/bin/vim /usr/local/bin/vim
  when: local_vim.stat.exists == False

- name: Show hidden files in Mac Finder
  shell: if [ `defaults read com.apple.Finder AppleShowAllFiles` == "true"  ]; then echo "Already enabled"; else defaults write com.apple.Finder AppleShowAllFiles true && killall Finder; fi
  when: ansible_distribution == 'MacOSX' 
